### ISSUE TITLE
[question] what's this?

### ISSUE THREAD

**Issue by mb6ockatf** [IvanIsak2000/PROXIUM#1]
there isn't enough description in README.md

**Comment by IvanIsak2000** [comment]
Awesome question, solved in 41c7a691a30b4a6fd3380f44b0b544051e497138

**Comment by IvanIsak2000** [comment]
@mb6ockatf 
Bro when are you going to learn golang or do you want to learn it?

**Comment by mb6ockatf** [comment]
@IvanIsak2000 personally, i did not plan on learning it yet. i have learned lua recently, and currently i'm busy with projects written in it. also, i'm interested in asm / c / c++
